apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: prebaked 
  janus-idp.io/tekton: prebaked
  backstage.io/kubernetes-id: prebaked
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: prebaked
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  