apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: prebaked
  janus-idp.io/tekton: prebaked
  backstage.io/kubernetes-id: prebaked
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: prebaked
resources: 
- deployment.yaml
- route.yaml
- service.yaml
